/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <functional>
#include "uart_engine.hpp"
#include "timer_engine.hpp"
#include "led_engine.hpp"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

UART_ENGINE uart3;
TIMER_ENGINE timer6;

int main(void)
{
  LED_Init();

  uart3.initialize();

  auto timer_action = [&]()
  {
      uart3.transmit("Hello from a proper C++ class!\r\n");
  };

  timer6.initialize(64000 - 1, 1000 - 1, timer_action);
  timer6.start();

  while(1){}
}
